# Generated by Django 5.2.7 on 2025-10-25 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='course',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='student',
            new_name='users',
        ),
    ]
